name: nemotron-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13.12
  - pip
  - pandas
  - requests
  - urllib3

  - pip:
      - ray
      - vllm
      - flashinfer-python==0.6.13
      - flashinfer-cubin==0.6.13